# Generated by Django 5.2.3 on 2025-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trisgame',
            name='board',
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_1_1',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_1_2',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_1_3',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_2_1',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_2_2',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_2_3',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_3_1',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_3_2',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='trisgame',
            name='square_3_3',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='trisgame',
            name='winner',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O'), ('Draw', 'Draw')], max_length=10),
        ),
    ]
